In [1]:
# Import libraries
import os,sys,tarfile,re
import time 
import numpy as np
import pandas as pd
import mdtraj as md
from biopandas.pdb import PandasPdb

import logging
from queue import Queue
from threading import Thread
from time import time

In [3]:
# Load a dcd file
dcdFile = '/net/jam-amaro-shared/dse_project/Spike_Dataset/TRAJECTORIES_spike_closed_prot_glyc_amarolab/spike_closed_prot_glyc_amarolab_1.dcd'
psfFile = '/net/jam-amaro-shared/dse_project/Spike_Dataset/TRAJECTORIES_spike_closed_prot_glyc_amarolab/spike_closed_prot_glyc_amarolab.psf'
dcd_traj = md.load(dcdFile, top = psfFile)

In [14]:
dcd_traj[0].save_pdb('.tmp.pdb')
pdb_df = PandasPdb().read_pdb('.tmp.pdb')
pdb_atom_df = pdb_df.df['ATOM']
glycan_mask =  pdb_atom_df.segment_id.apply(lambda x : True if re.match('G\d+', x) else False)
glycan_residues = pdb_atom_df[glycan_mask].residue_name.unique()

In [17]:
for i in range(1,71):

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
19507,ATOM,19510,,C1,,BGL,,C,1,,...,-23.230,71.608,219.401,1.0,0.0,,G1,C,NaN,19512
19508,ATOM,19511,,H1,,BGL,,C,1,,...,-24.312,71.396,219.537,1.0,0.0,,G1,H,NaN,19513
19509,ATOM,19512,,C5,,BGL,,C,1,,...,-23.742,73.748,220.390,1.0,0.0,,G1,C,NaN,19514
19510,ATOM,19513,,H5,,BGL,,C,1,,...,-24.816,73.487,220.504,1.0,0.0,,G1,H,NaN,19515
19511,ATOM,19514,,O5,,BGL,,C,1,,...,-23.127,73.057,219.259,1.0,0.0,,G1,O,NaN,19516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72754,ATOM,72830,,C6,,BGA,,X,2,,...,45.304,22.788,211.678,1.0,0.0,,G70,C,NaN,72832
72755,ATOM,72831,,H61,,BGA,,X,2,,...,45.541,21.767,211.310,1.0,0.0,,G70,H,NaN,72833
72756,ATOM,72832,,H62,,BGA,,X,2,,...,46.160,23.479,211.830,1.0,0.0,,G70,H,NaN,72834
72757,ATOM,72833,,O6,,BGA,,X,2,,...,44.446,23.361,210.662,1.0,0.0,,G70,O,NaN,72835
72758,ATOM,72834,,HO6,,BGA,,X,2,,...,44.640,24.268,210.416,1.0,0.0,,G70,H,NaN,72836

In [ ]:
# Find the glycans

In [ ]:
# Cluster glycans according to position across trajectory